version: "3.3"

networks:
  db:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: sconcy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: frauditsafe
    container_name: postgres
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    networks:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: saulconcy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    container_name: pgadmin
    depends_on:
      - postgres
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  front_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    container_name: frontend

volumes:
  postgres:
  pgadmin_data: